### ISSUE TITLE
Need Fabric

### ISSUE THREAD

**Issue by Xiaohuang257** [moewhite19/ChanLang#1]
您能尝试做个Fabric的版本吗（

**Comment by moewhite19** [comment]
> 您能尝试做个Fabric的版本吗（

我觉得没有吧x 这插件主要是用在插件端当前置插件用的x。用来获取物品，附魔之类的中文名称，更改语言是顺带。
  本身也不是什么优秀的插件x，一个好的语言插件应该还要能支持多语言不是吗
